config/routes.rb
Wjgzxt::Application.routes.draw do
  match 'log' => 'log_action#index'
  match 'log(/:action)' => 'log_action#(:action)'
  resources :log_action,only:[:index] do
    collection do
      get 'index','neg_r','neg_ru'
    end
  end

  resources :pwd_modify, only: [] do
    collection do
      get 'modify', 'p_modify'
    end
  end

  resources :domain, only: [] do
    collection do
      get 'validate', 'test', 'dfileupload'
      post 'upload'
    end
  end

  resources :export, only: [] do
    member do
      get 'modify', 'chg_status', 'del'
    end
    collection do
      get 'index', 'flag', 'perm_deni'
      get 'mdf', 'add_flag', 'p_add_flag'
    end
  end

  resources :rdata, only: [] do
    collection do
      get 'index','q_rdata_report'
    end
  end

  match 'login' => 'login#index'
  get 'login/index'
  post "login/login"
  get "login/logout"

  match 'workorders' => 'workorders#index'
  resources :workorders, only: [] do
    collection do
      get 'index', 'day_wo', 'week_wo', 'month_wo', 'wo_table', 'export_detail', 'week_table', 'month_table'
    end
  end

  match 'graphs' => 'graphs#index'
  resources :graphs, only: [] do
    collection do
      get 'index', 'data_json'
    end
  end

  resources :web_hit_rate, only: [] do
    collection do
      get 'time_r', 'select_day_report', 'select_month_report', 'index', 'day_r', 'month_r', 'list_day', 'list_time', 'list_locale'
      post 'day_r', 'month_r'
    end
  end

  match 'whr/' => 'web_hit_rate#index'

  resources :param_setting, only: [] do
    collection do
      get 'http', 'ping', 'route', 'video', 'adduser', 'mng_user', 'interaction', 'view_interaction', 'del_interaction', 'p_adduser'
      get 'u_user', 's_user', 'd_user', 'p_u_user', 'p_interaction'
      post 'p_adduser'
    end
  end

  match 'reports/get_data(.:format)' => 'reports#get_data'
  resources :reports, only: [] do
    collection do
      get 'export_rep', 'get_data', 'r_graph', 'locale_detail'
      get 'select_date_report', 'select_day_report', 'select_week_report', 'select_month_report'
      get 'time_report', 'day_report', 'week_report', 'month_report', 'day_report_csv', 'week_report_csv', 'month_report_csv'
      get 'date2time_report', 'date2day_report', 'date2week_report', 'date2month_report'
      post 'day_report', 'week_report', 'month_report'
    end
  end

  get 'reports/export_ranking'

  post 'reports/website_ranking'

  get 'reports/website_select'

  get 'reports/locale_ranking'

  get 'welcome/index'

  match 'reports/' => 'reports#index'
  match 'welcome/' => 'welcome#index'

  root :to => 'login#index'

end

app/helpers/reports_helper.rb
#encoding : utf-8

require 'csv'
require 'will_paginate/array'
module ReportsHelper
  BACKBONE  = '广东铁通6-gddx(bgp)联通出口'
  #骨干为null，自租出口非null
  ZZNOTNULL = 2
  #骨干不为null,而自租出口为null
  ZZNULL    = -2

  #骨干出口有效数据
  def blackbone_data_valid
    #backbone_data     = HttpTestData.where('source_node_name = ? and test_time >= ? and test_time < ?', BACKBONE, Time.parse('2013-03-1 21:00:00'),Time.parse('2013-03-1 22:00:00'))
    backbone_data     = HttpTestData.where(:test_time.gte => Time.parse('2013-03-1 21:00:00'), :test_time.lt => Time.parse('2013-03-1 22:00:00'), :source_node_name => BACKBONE)
    new_backbone_data = []
    backbone_data.each do |bline|
      host_locale =''
      if !bline.dest_locale.blank? && bline.dest_locale.to_s.strip != 'NULL'
        host_locale = bline.dest_locale.to_s.strip
      end

      #判断自租出口数据是否有效的条件
      #目前只监测联通和电信出口
      if  !host_locale.blank? && host_locale == '联通' || host_locale == '电信'
        new_backbone_data << bline
        puts 'blackbone'+'-'*100+bline.id.to_s
      end
    end
    backbone_data
  end

  #对自租出口提取有效数据
  def other_data_valid
    #other_data = HttpTestData.where('source_node_name != ? and test_time >= ? and test_time < ?', BACKBONE, Time.parse('2013-03-1 21:00:00'),Time.parse('2013-03-1 22:00:00'))
    other_data = HttpTestData.where(:test_time.gte => Time.parse('2013-03-1 21:00:00'), :test_time.lt => Time.parse('2013-03-1 22:00:00'), :source_node_name.ne => BACKBONE)
    new_data   =[]
    other_data.each do |line|
      source_node_arr = line.source_node_name.to_s.strip[-4..-3]
      host_locale     =''
      if !line.dest_locale.blank? && line.dest_locale.to_s.strip != 'NULL'
        host_locale = line.dest_locale.to_s.strip
      end

      #判断自租出口数据是否有效的条件
      #出口与归属地必须要一致才有效
      if !source_node_arr.blank? && !host_locale.blank? && (source_node_arr == host_locale)
        new_data << line
        puts 'other'+'-'*100+line.id.to_s
      end
    end
    new_data
  end

  def gen_report_data(time_begin, time_end, ef)
    etn        = user_perm_ename_list(ef)

    #psc        = ParamScoreConfig.where('param_type = ? and weight > ? ', 'htd', 0)
    psc        = ParamScoreConfig.where(param_type: 'htd', :weight.gt => 0)
    title_name = []
    key1       = %w( source_node_name dest_node_name)
    key2       =%w(positive_items_scores negative_items_scores total_scores)

    key3 = []
    psc.each do |config|
      title_name << config.alias
      key3 << config.param_name
    end
    key = key1 + key3 + key2

    odata = []
    etn.each do |ename|
      en_tmp   = ExportName.where(alias: ename).first.name
      #tmp_data = HttpTestScore.select(key).where('test_time >= ? and test_time < ?', time_begin, time_end).order('total_scores DESC').paginate page: params[:page], per_page: 10
      #tmp_data = HttpTestScore.select(key).where('test_time >= ? and test_time < ? and source_node_name = ?', time_begin, time_end, ename)
      tmp_data = HttpTestScore.where(:test_time.gte => time_begin, :test_time.lt => time_end, source_node_name: ename)
      unless tmp_data.blank?
        tmp_data.each do |line|
          tarr = []
          tarr << en_tmp
          tarr << line.dest_node_name
          tarr << line.time_to_index << line.total_time << line.throughput_time << line.connection_sr << line.index_page_loading_sr
          tarr << line.positive_items_scores << line.negative_items_scores << line.total_scores
          odata << tarr
        end
      end
    end
=begin
    unless odata.blank?
      odata.sort_by! { |x| x[9] }
    end
=end
    [title_name, odata.paginate(page: params[:page], per_page: 10)]
  end

  def gen_report_csv(time_begin, time_end, ef)
    etn        = user_perm_ename_list(ef)

    #psc        = ParamScoreConfig.where('param_type = ? and weight > ? ', 'htd', 0)
    psc        = ParamScoreConfig.where(param_type: 'htd', :weight.gt => 0)
    title_name = []
    key1       = %w(test_time source_node_name source_ip_address source_group dest_node_name dest_url dest_group)
    key2       =%w(dest_ip_address dest_nationality dest_province dest_locale positive_items negative_items equal_items positive_items_scores
negative_items_scores equal_items_scores total_scores)

    key3 = []
    psc.each do |config|
      title_name << config.alias
      key3 << config.param_name
    end
    key = key1 + key3 + key2

    odata = []
    etn.each do |ename|
      #tmp_data = HttpTestScore.select(key).where('test_time >= ? and test_time < ? and source_node_name = ?', time_begin, time_end, ename)
      tmp_data = HttpTestScore.where(:test_time.gte => time_begin, :test_time.lt => time_end, source_node_name: ename)
      odata    += tmp_data
    end
    #odata.sort_by! { |x| x[9] }

    #odata = HttpTestScore.select(key).where('test_time >= ? and test_time < ?', time_begin, time_end).order('source_node_name')
    return key, odata, title_name
  end

  def user_perm_ename_list(ef)
    etn = Set.new

    if ef.blank?
      #查询当月的月表数据
      #en = ExportName.where('user_id != 0')
      #en = ExportName.where(:user_id.ne => 0)
      en = ExportName.where(:status => 0)
      en.each do |line|
        unless line.alias.blank?
          etn << line.alias
        end
      end
    else
      ef.each do |t|
        unless t.alias.blank?
          etn << t.alias
        end
      end
    end
    #将对比标杆出口去掉
    etn.delete(BACKBONE)
    etn
  end

  def data_to_csv(title, key, data, option={})
    puts '-'*30+key.to_s
    CSV.generate(option) do |csv|
      #csv << %w(结果时间 源节点名称 源测试地址  源信息:分组名 目的节点名称 目的测试地址 目的信息:分组名 解析时间 连接时间 首字节时间
      #        首屏打开时间 下载时间 页面加载时间 总时间 吞吐率 综合质量 解析成功率 连接成功率  首页加载成功率 加载比例
      #        成功率 结果IP地址 结果国家名称 结果省名称 结果归属地 下载大小 内容大小 返回码 附加项 元素数量
      #        正分项数量 负分项数量 相等项数量 正项总分 负项总分 相等项总分 所有项总分)
      csv << %w(结果时间 源节点名称 源测试地址  源信息:分组名 目的节点名称 目的测试地址 目的信息:分组名) + title + %w(结果IP地址 结果国家名称 结果省名称 结果归属地 正分项数量 负分项数量 相等项数量 正项总分 负项总分 相等项总分 所有项总分)
      data.each do |tdata|
        tmp1 = [tdata.test_time, tdata.source_node_name, tdata.source_ip_address, tdata.source_group, tdata.dest_node_name, tdata.dest_url,
                tdata.dest_group]
        tmp2 = [tdata.dest_ip_address, tdata.dest_nationality, tdata.dest_province, tdata.dest_locale, tdata.positive_items, tdata.negative_items,
                tdata.equal_items, tdata.positive_items_scores, tdata.negative_items_scores, tdata.equal_items_scores, tdata.total_scores]
        tmp3 = []
        key.each do |k|
          case k
            when 'resolution_time'
              tmp3 << tdata.resolution_time
            when 'connection_time'
              tmp3 << tdata.connection_time
            when 'time_to_first_byte'
              tmp3 << tdata.time_to_first_byte
            when 'time_to_index'
              tmp3 << tdata.time_to_index
            when 'page_download_time'
              tmp3 << tdata.page_download_time
            when 'page_loading_time'
              tmp3 << tdata.page_loading_time
            when 'total_time'
              tmp3 << tdata.total_time
            when 'throughput_time'
              tmp3 << tdata.throughput_time
            when 'overall_quality'
              tmp3 << tdata.overall_quality
            when 'resolution_sr'
              tmp3 << tdata.resolution_sr
            when 'connection_sr'
              tmp3 << tdata.connection_sr
            when 'index_page_loading_sr'
              tmp3 << tdata.index_page_loading_sr
            when 'page_loading_r'
              tmp3 << tdata.page_loading_r
            when 'loading_sr'
              tmp3 << tdata.loading_sr
            else
          end
        end
        tmp = tmp1 + tmp3 + tmp2

        csv << tmp
        #csv << [tdata.test_time, tdata.source_node_name, tdata.source_ip_address, tdata.source_group, tdata.dest_node_name, tdata.dest_url,
        #        tdata.dest_group, tdata.resolution_time, tdata.connection_time, tdata.time_to_first_byte, tdata.time_to_index,
        #        tdata.page_download_time, tdata.page_loading_time, tdata.total_time, tdata.throughput_time, tdata.overall_quality,
        #        tdata.resolution_sr, tdata.connection_sr, tdata.index_page_loading_sr, tdata.page_loading_r, tdata.loading_sr,
        #        tdata.dest_ip_address, tdata.dest_nationality, tdata.dest_province, tdata.dest_locale, tdata.download_size, tdata.contents_size,
        #        tdata.return_code, tdata.add_ons, tdata.element_number, tdata.positive_items, tdata.negative_items, tdata.equal_items,
        #        tdata.positive_items_scores, tdata.negative_items_scores, tdata.equal_items_scores, tdata.total_scores]
      end
    end
  end

  def cal_score(cons_data, odata)
    t_score = 0
    if cons_data == 'NULL'
      if odata != 'NULL'
        t_score = ZZNOTNULL
      end
    else
      if odata == 'NULL'
        t_score = ZZNULL
      elsif odata.to_s.to_f < cons_data.to_s.to_f
        t_score += 1
      elsif cons_data.to_s.to_f <= odata.to_s.to_f && odata.to_s.to_f <= cons_data.to_s.to_f * 2
        t_score += 0
      elsif cons_data.to_s.to_f*2 < odata.to_s.to_f
        t_score += -1
      end
    end
    t_score
  end

  def statis_score(arr)
    positive_items     = 0
    equal_items        = 0
    negative_items     = 0
    positive_i_scores  = 0
    equal_items_scores = 0
    negative_i_scores  = 0

    arr.each do |element|
      if element > 0
        positive_items    += 1
        positive_i_scores += element
      elsif element < 0
        negative_items    += 1
        negative_i_scores += element
      else
        equal_items        += 1
        equal_items_scores += element
      end
    end
    [positive_items, positive_i_scores, negative_items, negative_i_scores, equal_items, equal_items_scores]
  end

  def cal_export_ranking(time_begin, time_end, ef = [])
    etn = Set.new

    if ef.blank?
      #查询当月的月表数据
      #en = ExportName.all
      en = ExportName.where(status: 0)
      en.each do |line|
        unless line.alias.blank?
          etn << line.alias
        end

app/views/reports/date2time_report.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '报表查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>时刻点所对应的得分排名表</h1>

        <p>
          本排名表提取指定时刻的评分数据而生成，各项评分均根据其所对应的评分规则进行处理，如对结果有异议，可申请核对。
        </p>
        <br/>

        <p class="hidden-phone">
          <a class="btn btn-info btn-large pull-right">详细指南请猛击此处 &raquo;...</a>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <a href="/reports">
            <i class="radmin-icon radmin-file"></i>
            测试评分报表
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          选择日周月报表
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">出口得分排名表如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">源结节名称</th>
              <th style="text-align:center;">目的节点名称</th>
              <% @title_name.each do |tn| %>
                <th style="text-align:center;"><%= tn %></th>
              <% end %>
              <th style="text-align:center;">总正分</th>
              <th style="text-align:center;">总负分</th>
              <th style="text-align:center;">总分</th>
            </tr>
            </thead>
            <tbody>
            <% @odata.each do |line| %>
              <tr>
                <td style="text-align:center;"><%= line[0] %></td>
                <td style="text-align:center;"><%= line[1] %></td>
                <td style="text-align:center;"><%= line[2] %></td>
                <td style="text-align:center;"><%= line[3] %></td>
                <td style="text-align:center;"><%= line[4] %></td>
                <td style="text-align:center;"><%= line[5] %></td>
                <td style="text-align:center;"><%= line[6] %></td>
                <td style="text-align:center;"><%= line[7] %></td>
                <td style="text-align:center;"><%= line[8] %></td>
                <td style="text-align:center;"><span class="label label-info"><%= line[9] %></span></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <div class="well center">
        <div class="pagination pagination-small center offset4">
          <%= will_paginate @odata, :inner_window => 2 %>
        </div>
        <div class="offset4">
          统计信息：一共有 <%= @odata.total_entries %>  条,当前第 <%= @odata.current_page %> 页, 共
          <% if (@odata.total_entries % @odata.per_page) ==0 %>
            <%= (@odata.total_entries / @odata.per_page) %> 页.
          <% else %>
            <%= (@odata.total_entries / @odata.per_page) +1 %> 页
          <% end %>
        </div>

      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/reports/day_report.html.erb
<h1>Reports#day_report</h1>
<p>Find me in app/views/reports/day_report.html.erb</p>

app/views/reports/export_ranking.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '报表查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>出口得分排名表</h1>

        <p>
          本排名表根据出口对各个测试网站的评分进行统计，主要统计负分、总分两项指标。<br/>
          计算方法是：出口得分 / 有效匹配网站数，从而得出平均值。因为每个出口所匹配的有效数不一致，只能取其平均值。<br/>
          目前本系统中含最新一次测试数据中含电信方向出口共 <%= @dx %> 个,联通方向出口共 <%= @lt %> 个，其它方向出口共 <%= @oe %> 个暂未纳入评分。如对结果有异议，可申请核对。
        </p>
        本次统计区间 <span class="label label-warning">[<%= @time_begin.localtime.strftime('%Y年-%m月%d日 %H:%M:%S') %>]</span> -
        <span class="label label-warning">[<%= @time_end.localtime.strftime('%Y年-%m月%d日 %H:%M:%S') %>]</span> ，数据如下示：
        总分是正分的有 <%= @total_pos %> 个，总分是负分的有 <%= @total_neg %>个,总分为0分的有 <%= @total_eql %> 个。
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <a href="/">
            <i class="radmin-icon radmin-home"></i>
            首页
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="/reports">
            <i class="radmin-icon radmin-file"></i>
            报表查看
          </a>
          <span class="divider">/</span>
        </li>
        <li>
          <a href="/reports/export_rep">
            <i class="radmin-icon radmin-file"></i>
            选择日周月报表
          </a>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <i class="radmin-icon radmin-file"></i>
          查看日周月报表
        </li>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span6">
          <h4 class="title">电信出口得分排名表如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">出口名称</th>
              <th style="text-align:center;">负值</th>
              <th style="text-align:center;">总分</th>
              <th style="text-align:center;">负分网站数</th>
              <th style="text-align:center;">有效网站数</th>
              <th style="text-align:center;">正分网站率</th>
            </tr>
            </thead>
            <tbody>
            <% @dx_array.each_with_index do |line, i| %>
              <tr>
                <td style="text-align:center;"><%= link_to line[0],action:'r_graph',:en => line[0] %></td>
                <td style="text-align:center;">
                  <% if line[1].to_s.to_f < 0 %>
                    <span class="label label-important"><%= number_with_precision line[1].to_s.to_f %></span>
                  <% else %>
                    <span class="label label-info"><%= number_with_precision line[1].to_s.to_f %></span>
                  <% end %>
                </td>
                <td style="text-align:center;">
                  <% if line[2].to_s.to_f < 0 %>
                    <span class="label label-important"><%= number_with_precision line[2].to_s.to_f %></span>
                  <% else %>
                    <span class="label label-info"><%= number_with_precision line[2].to_s.to_f %></span>
                  <% end %>
                </td>
                <td style="text-align:center;"><span class="label label-info"><%= line[3] %></span></td>
                <td style="text-align:center;"><span class="label label-info"><%= line[4] %></span></td>
                <td style="text-align:center;"><span class="label label-info"><%= number_with_precision line[5], :precision => 2 %></span></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class="span6">
          <h4 class="title">联通出口得分排名表如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">出口名称</th>
              <th style="text-align:center;">负值</th>
              <th style="text-align:center;">总分</th>
              <th style="text-align:center;">负分网站数</th>
              <th style="text-align:center;">有效网站数</th>
              <th style="text-align:center;">正分网站率</th>
            </tr>
            </thead>
            <tbody>
            <% @lt_array.each_with_index do |line, i| %>
              <tr>
                <td style="text-align:center;"><%= link_to line[0],action:'r_graph',:en => line[0] %></td>
                <td style="text-align:center;">
                  <% if line[1].to_s.to_f < 0 %>
                    <span class="label label-important"><%= number_with_precision line[1].to_s.to_f %></span>
                  <% else %>
                    <span class="label label-info"><%= number_with_precision line[1].to_s.to_f %></span>
                  <% end %>
                </td>
                <td style="text-align:center;">
                  <% if line[2].to_s.to_f < 0 %>
                    <span class="label label-important"><%= number_with_precision line[2].to_s.to_f %></span>
                  <% else %>
                    <span class="label label-info"><%= number_with_precision line[2].to_s.to_f %></span>
                  <% end %>
                </td>
                <td style="text-align:center;"><span class="label label-info"><%= line[3] %></span></td>
                <td style="text-align:center;"><span class="label label-info"><%= line[4] %></span></td>
                <td style="text-align:center;"><span class="label label-info"><%= number_with_precision line[5], :precision => 2 %></span></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>

app/views/reports/graph.html.erb
<%= provide(:body_id, 'graphs') %>
<%= provide(:result, '系统说明') %>



<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>图表&数据</h1>

        <p>
          系统通过提取每日各测试点数据生成以下图表，如对结果有异议，可申请进行核对。
        </p>

        <p class="hidden-phone">
          <a class="btn btn-info btn-large pull-right">详细指南请猛击此处 &raquo;...</a>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <h3 class="welcome">
        <div id="myGrphsJson" style="width:100%; height:100%;overflow-x:auto;overflow-y:auto">

        </div>
      </h3>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span10">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small>Jane Doe via Mobile</small>
      </blockquote>
    </div>
    <div class="span2">
      <div class="controls pull-right">
        <button class="btn btn-mini btn-info">Edit</button>
        <button class="btn btn-mini btn-danger">Delete</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    var myChart1 = new FusionCharts('/FusionCharts/Scatter.swf', 'myChartSome', '4000', '300','0','1');
    myChart1.setJSONUrl("/reports/get_data.json?en=<%= @en %>");
    myChart1.render('myGrphsJson');
</script>

app/views/reports/locale_ranking.html.erb
<%= provide(:body_id, 'index') %>
<%= provide(:result, '报表查看') %>

<div class="container-fluid content-wrapper">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit">
        <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
        <h1>归属地数据报表</h1>

        <p>
          本排名表根据各个出口对同一网站的各项测试得分进行统计，只统计总分此项指标，如对结果有异议，可申请核对。
        </p>
        <br/>

        <p class="hidden-phone">
          <a class="btn btn-info btn-large pull-right">详细指南请猛击此处 &raquo;...</a>
        </p>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid hidden-desktop hidden-phone">
        <div class="span12">
          <h4 class="title">归属地数据汇总如下示：</h4>

          <div class="squiggly-border"></div>
          <table class="table table-striped table-bordered table-radmin">
            <thead>
            <tr>
              <th style="text-align:center;">归属地名称</th>
              <th style="text-align:center;">测试网站数量</th>
              <th style="text-align:center;">详细信息</th>
            </tr>
            </thead>
            <tbody>
            <% @locale.each do |key, value| %>
              <tr>
                <td style="text-align:center;"><%= key %></td>
                <td style="text-align:center;"><span class="label label-info"><%= value %></span></td>
                <td style="text-align:center;">
                  <a class="btn btn-small btn-info" href="<%= locale_detail_reports_path(lc: key) %>">
                    <i class="icon-edit icon-white"></i>
                    查看详细信息
                  </a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <p></p>

  <div class="row-fluid">
    <div class="span12">
      <h4 class="title">名言警句</h4>

      <div class="squiggly-border"></div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <blockquote>
        <p>
          Etiam varius erat in nisl egestas id auctor lacus consectetur.
          Ut dui risus, auctor a malesuada volutpat, tempus sit amet arcu.
        </p>
        <small class="pull-right">Jane Doe via Mobile</small>
      </blockquote>
    </div>
  </div>
</div>